export const SUPPORTER_CREATE_REQUEST = 'SUPPORTER_CREATE_REQUEST'
export const SUPPORTER_CREATE_SUCCESS = 'SUPPORTER_CREATE_SUCCESS'
export const SUPPORTER_CREATE_FAIL = 'SUPPORTER_CREATE_FAIL'

export const SUPPORTER_LIST_REQUEST = 'SUPPORTER_LIST_REQUEST'
export const SUPPORTER_LIST_SUCCESS = 'SUPPORTER_LIST_SUCCESS'
export const SUPPORTER_LIST_FAIL = 'SUPPORTER_LIST_FAIL'